### ISSUE TITLE
Color of background Problem

### ISSUE THREAD

**Issue by kungen32** [Arch-Mina/Assets-Editor#1]
Hello,

I have used thousands of sprites, i have decided to upgrade to version 12.60, assets editor is working perfect ( create item not works but not need it right now )
I Want replace some customs sprits to anothers, this one works with sprites extracted but sprites maded with same background not show item in game, show as a Blank Square, and some others are working, from where come the problem ? I tried to many differents background, also have imported threes with Black background and it's show correctly in game, i dont understand how it works completly
![3](https://user-images.githubusercontent.com/77188623/110222659-1bd45980-7ed4-11eb-81fd-b921040de510.png)
![5](https://user-images.githubusercontent.com/77188623/110222690-5f2ec800-7ed4-11eb-95a9-92b91265755c.png)

**Comment by Arch-Mina** [comment]
Hello,
Make sure your sprites have a transparent background, not magenta.
about the create it should work fine if you filled all the field right, no 0 as value or empty field

**Comment by kungen32** [comment]
Hello, thanks for your reply, creating is working you are right, 
but about the transaprency.. have removed all, added an alpha canal, showing white ( using gimp )
Also i tried to cut the picture with photoshop and remove background, in program shows helmet correctly and black background 
![Sans titre](https://user-images.githubusercontent.com/77188623/110232305-26671100-7f1d-11eb-93db-a053696c3543.png)

![item_33741](https://user-images.githubusercontent.com/77188623/110232243-ed2ea100-7f1c-11eb-9296-b5ee6c2ce291.png)

**Comment by Arch-Mina** [comment]
Not quite sure but maybe try to export that sprite as BMP and reimport it
about the auto slice, it will only work if your sheet size equal to or more than 384X384

**Comment by kungen32** [comment]
Ok, for the last i have added more sprites and giving more big picture, is now working, but about 1 x 1 in 32 x 32 showing correctly in program, but blank square in game, how we can expect fix it ? I try this morning create a grid and adding all custom sprites as a Big picture 512x512 and not working in game also

**Comment by kungen32** [comment]
How we can add more than 12 Lines of sprites in importation ? Like a 60 lines 32x32 / 60x25 squares for example ?
