### ISSUE TITLE
[CRASH]  When you edit an item to have animation it closes the application

### ISSUE THREAD

**Issue by LeoTKBR** [Arch-Mina/Assets-Editor#11]
Currently I am trying to modify the tibia coin token sprite and add an animated sprite, however when adding animation to the token item it closes.

You can see how it behaves in the gif below

![CrashAssets](https://github.com/Arch-Mina/Assets-Editor/assets/41605307/17fc8384-b8e5-4b1d-a3f0-e57251a3631c)

**Comment by Arch-Mina** [comment]
which client version you're using?
can you confirm if sprite id 158019 exists?

**Comment by LeoTKBR** [comment]
I'm using cipsoft client 13.21
