### ISSUE TITLE
Sprite Sheet

### ISSUE THREAD

**Issue by Peixonauta2** [Arch-Mina/Assets-Editor#2]
Hello, I've been using this tool for a while but I don't have enough knowledge to do it myself: is that possible to implement 128x128 sprite sheets?

**Comment by Arch-Mina** [comment]
Hi
do you mean the resolution of sprite instead of 32X32 to be 128X128?
in this case I belive it's client side

**Comment by Peixonauta2** [comment]
No, I don't think thats possible. What I mean is something like this:

![image](https://user-images.githubusercontent.com/63183357/126876621-a8c759bb-68dc-40fe-bd27-71babe62562f.png)

Now we have 32x32, 32x64, 64x32 and 64x64 sheet size. Is it possible to implement 128x128 size?

**Comment by Arch-Mina** [comment]
the client supports these 4 types only

**Comment by Peixonauta2** [comment]
Thats sad, thanks for your attention.
