### ISSUE TITLE
#ff00ff (pink) outline

### ISSUE THREAD

**Issue by vasconcellosdevictor** [Arch-Mina/Assets-Editor#40]
Please, there is a easy way to remove that pink outline?

![image](https://github.com/user-attachments/assets/d7e68387-9b9f-4c92-94c7-e8858fb4affc)
![image](https://github.com/user-attachments/assets/00ce77c2-4546-40ee-8fba-a1ba881c9602)
![image](https://github.com/user-attachments/assets/eb0c0d2b-d17a-420c-aadf-bb0d67993fdf)
![image](https://github.com/user-attachments/assets/29191f88-3b1f-48dc-8d2e-ba444cdf2d88)
![image](https://github.com/user-attachments/assets/1f66b8b3-1c58-4a54-8984-b2e7f0d02b46)

Ty

**Comment by vasconcellosdevictor** [comment]
![image](https://github.com/user-attachments/assets/833d0628-a71f-4bdc-9b60-af87553d59bb)

I've already tried using background collor #ff00ff or transparent background, both resulting in the same pink outline.

**Comment by lamonato29** [comment]
Bro, i guess you have more than one pink color in your sprite

**Comment by vasconcellosdevictor** [comment]
Nevermind. I've found the cause. The problem is due to missing pixels or pixels that are 'transparent'.
